---
title: "Exploratory Data Analysis"
output:
  html_document:
    toc: yes
    toc_depth: 2
    number_sections: yes  
    toc_float:
      collapsed: no  # Ensure Level 1 & 2 remain expanded
      smooth_scroll: yes
---


```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<br>

# Reading in data {#ch7}


------------------------------------------------------------------------------------------------------------------------

<br><br>

# Summary Statistics {#ch8}

```{r child="zpg_T8_Summary.Rmd"}
```

------------------------------------------------------------------------------------------------------------------------

<br><br>

# Filtering/Selecting {#ch9}

```{r child="zpg_T9_Wrangle.Rmd"}
```

------------------------------------------------------------------------------------------------------------------------


<br><br>

# Missing data {#ch10}

```{r child="zpg_T10_Missing.Rmd"}
```

------------------------------------------------------------------------------------------------------------------------


<br><br>

# Plots {#ch11}

------------------------------------------------------------------------------------------------------------------------

<br><br>

