<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>in_T17_ConfPred.knit</title>

<script src="site_libs/header-attrs-2.29/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/flatly.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/textmate.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>






<link rel="stylesheet" href="styles.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html"></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Full Tutorial List</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    R-BASICS
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="CH1_BASICS.html#ch1">1 Installing/Accessing R</a>
    </li>
    <li>
      <a href="CH1_BASICS.html#ch2">2 Changing Settings</a>
    </li>
    <li>
      <a href="CH1_BASICS.html#ch3">3 Console/coding basics</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    STARTING EACH LAB
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="CH2_EACHLAB.html#ch4">4. Projects</a>
    </li>
    <li>
      <a href="CH2_EACHLAB.html#ch5">5. Packages</a>
    </li>
    <li>
      <a href="CH2_EACHLAB.html#ch6">6. R-Markdown</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    EXPLORING DATA
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="in_T07_ReadingInData.html">7. Reading in data</a>
    </li>
    <li>
      <a href="CH3_EDA.html#ch8">8. Summary Statistics</a>
    </li>
    <li>
      <a href="CH3_EDA.html#ch9">9. Filtering/selecting</a>
    </li>
    <li>
      <a href="CH3_EDA.html#ch10">10. Missing Data</a>
    </li>
    <li>
      <a href="in_T11_Plots.html">11. Plots</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    STATISTICAL-ANALYSIS
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="in_T12_NormalDistributionsTTests.html">12. Normal/T-Dist/Tests</a>
    </li>
    <li>
      <a href="in_T13_Correlation.html">13 Correlation</a>
    </li>
    <li>
      <a href="in_T14_Regression.html">14. Simple Linear Regression</a>
    </li>
    <li>
      <a href="in_T15_Diagnostics.html">15. Model Diagnostics</a>
    </li>
    <li>
      <a href="in_T16_Outliers.html">16. Outliers</a>
    </li>
    <li>
      <a href="in_T17_ConfPred.html">17. Confidence &amp; Prediction</a>
    </li>
    <li>
      <a href="in_T18_Transformations.html">18. Transformations</a>
    </li>
    <li>
      <a href="in_T19_MLR.html">19. Multiple Linear Regression</a>
    </li>
    <li>
      <a href="in_T20_GLM.html">20. General Linear Regression</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">




</div>


<div id="confidence-and-prediction-intervals" class="section level1"
number="1">
<h1><span class="header-section-number">1</span> Confidence and
Prediction Intervals</h1>
<div id="what-are-they" class="section level2" number="1.1">
<h2><span class="header-section-number">1.1</span> What are they?</h2>
<p>Essentially these are two different things:</p>
<p><strong>Confidence interval:</strong> “Error bar” on the location of
the regression line at any specific value of x, or “what is the
uncertainty on the population mean of <span
class="math inline">\(y\)</span>, for a specific value of <span
class="math inline">\(x\)</span>?”</p>
<p><strong>Prediction interval:</strong> Predicting the range of likely
y-values for a new data-point, or “if you had to put a new dot on the
scatterplot, what range of y values would it likely be found in</p>
<p>These are described in detail here:</p>
<ul>
<li><a href="https://online.stat.psu.edu/stat462/node/125/"
class="uri">https://online.stat.psu.edu/stat462/node/125/</a></li>
<li><a href="https://online.stat.psu.edu/stat462/node/126/"
class="uri">https://online.stat.psu.edu/stat462/node/126/</a></li>
<li><a href="https://online.stat.psu.edu/stat462/node/127/"
class="uri">https://online.stat.psu.edu/stat462/node/127/</a></li>
<li><a href="https://online.stat.psu.edu/stat462/node/128/"
class="uri">https://online.stat.psu.edu/stat462/node/128/</a></li>
</ul>
<p>In R, lets look at the pirate dataset</p>
<pre class="r"><code>#For our pirate weight/height dataset
lm.pirate &lt;- lm(weight~height,data=pirates)
summary(lm.pirate)</code></pre>
<pre><code>## 
## Call:
## lm(formula = weight ~ height, data = pirates)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -12.3592  -2.6564  -0.0708   2.7275  11.1451 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -68.87722    1.71250  -40.22   &lt;2e-16 ***
## height        0.81434    0.01003   81.16   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.928 on 998 degrees of freedom
## Multiple R-squared:  0.8684, Adjusted R-squared:  0.8683 
## F-statistic:  6587 on 1 and 998 DF,  p-value: &lt; 2.2e-16</code></pre>
<p><br><br></p>
</div>
<div id="calculating-a-confidence-interval" class="section level2"
number="1.2">
<h2><span class="header-section-number">1.2</span> Calculating a
confidence interval</h2>
<p><strong>What are the AVERAGE WEIGHTS (and uncertainty on our
estimate) of pirates whose heights are 150cm and 170cm?</strong></p>
<pre class="r"><code># So we have the MODEL
lm.pirate &lt;- lm(weight~height,data=pirates)


# a mini table of our new X-Values - you need the column name to be identical to your predictor
new.pirates &lt;- data.frame(height=c(150,170))


# and the command
# predict (MODEL_NAME ,  NAME_OF_NEW_DATA,  TYPE_OF_INTERVAL, SIG LEVEL)
predict(lm.pirate,newdata=new.pirates,interval=&quot;confidence&quot;,level=0.95)</code></pre>
<pre><code>##        fit      lwr      upr
## 1 53.27345 52.80652 53.74037
## 2 69.56020 69.31640 69.80400</code></pre>
<p>We are 95% certain that on average, the AVERAGE weight of pirates who
are 150cm tall falls between 52.8 Kg and 53.74 Kg.</p>
<p>We are 95% certain that on average, the AVERAGE weight of pirates who
are 170cm tall falls between 69.32 Kg and 69.80 Kg.</p>
<p><br><br></p>
</div>
<div id="calculating-a-prediction-interval" class="section level2"
number="1.3">
<h2><span class="header-section-number">1.3</span> Calculating a
prediction interval</h2>
<p><strong>A new pirate joins and her height is 160cm. What range of
weights is she likely to have? with a significance level of
99%</strong></p>
<pre class="r"><code># So we have the model
# MAKE SURE THAT YOU ONLY MENTION THE TABLE-NAME AT THE END
lm.pirate &lt;- lm(weight~height,data=pirates)


# a mini table of our new X-Values - you need the column name to be identical to your predictor
new.pirates &lt;- data.frame(height=c(160))


# and the command
# predict (MODEL_NAME ,  NAME_OF_NEW_DATA,  TYPE_OF_INTERVAL, SIG LEVEL)
predict(lm.pirate,newdata=new.pirates,interval=&quot;predict&quot;,level=0.99)</code></pre>
<pre><code>##        fit      lwr      upr
## 1 61.41682 51.27067 71.56298</code></pre>
<p>Given our model, her weight is likely to be somewhere between 51.27
Kg and 71.56 Kg with 99% certainty.</p>
</div>
<div id="help-my-code-doesnt-work" class="section level2" number="1.4">
<h2><span class="header-section-number">1.4</span> HELP! MY CODE DOESN’T
WORK</h2>
<div id="predictormodel-name-spelt-wrong" class="section level3"
number="1.4.1">
<h3><span class="header-section-number">1.4.1</span> Predictor/model
name spelt wrong</h3>
<p>If you don’t spell your column name EXACTLY (case sensitive) the same
as the predictor in your model, the code will break. Here I put HEIGHT
not height for my new predictor:</p>
<pre class="r"><code># THIS WILL LOOK FINE BUT BREAK PREDICT.
# ONLY MENTION THE WORD PIRATES AFTER THE DATA BIT
lm.pirate &lt;- lm(weight~height,data=pirates)

new.pirates &lt;- data.frame(HEIGHT=c(160))
predict(lm.pirate,newdata=new.pirates,interval=&quot;predict&quot;,level=0.99)</code></pre>
<pre><code>## Error in eval(predvars, data, env): object &#39;height&#39; not found</code></pre>
</div>
<div id="your-original-lm-command" class="section level3"
number="1.4.2">
<h3><span class="header-section-number">1.4.2</span> Your original lm
command</h3>
<p>The <code>predict</code> command is fussy and depends on your
original <code>lm</code> command being exactly correct, where you only
type the name of the data.table once at the end. If you type it at each
stage, then the model doesn’t understand it all comes from one table,
which means that predict will run, but give the wrong answer.</p>
<p>For example</p>
<pre class="r"><code># this is correct
# lm_correct &lt;- lm(weight~height,data=pirates)

# If you add the data name at each step, the predict behaves wrongly
# THIS WILL WORK FINE INITIALY BUT CAUSE ISSUES FOR PREDICT
lm_WRONG &lt;- lm(pirates$weight~pirates$height,data=pirates)

new.pirates &lt;- data.frame(height=c(160))
predict(lm_WRONG,newdata=new.pirates,interval=&quot;predict&quot;,level=0.99)</code></pre>
<pre><code>##            fit      lwr       upr
## 1     72.09279 61.94981  82.23577
## 2    101.52296 91.33004 111.71587
## 3     69.51948 59.37678  79.66219
## 4     48.62358 38.45866  58.78849
## 5     59.66600 49.51823  69.81376
## 6     86.00982 75.85394  96.16570
## 7     59.82887 49.68126  69.97647
## 8     71.61233 61.46946  81.75521
## 9     65.13835 54.99459  75.28211
## 10    80.57005 70.42151  90.71859
## 11    63.44452 53.29984  73.58921
## 12    64.38916 54.24503  74.53329
## 13    70.40711 60.26439  80.54984
## 14    76.06676 65.92207  86.21145
## 15    67.64651 57.50359  77.78943
## 16    65.56995 55.42638  75.71352
## 17    75.68402 65.53956  85.82848
## 18    60.03245 49.88505  70.17985
## 19    72.06022 61.91725  82.20319
## 20    73.99834 63.85474  84.14195
## 21    84.07984 73.92690  94.23278
## 22    76.93810 66.79282  87.08338
## 23    60.32561 50.17849  70.47273
## 24    73.86805 63.72450  84.01160
## 25    83.79483 73.64229  93.94736
## 26    56.15620 46.00430  66.30810
## 27    70.76542 60.62267  80.90818
## 28    75.29314 65.14890  85.43738
## 29    49.99981 39.83769  60.16192
## 30    40.95252 30.76858  51.13645
## 31    91.29488 81.12905 101.46070
## 32    79.29154 69.14429  89.43878
## 33    85.86324 75.70760  96.01889
## 34    63.53410 53.38948  73.67873
## 35    76.27034 66.12552  86.41517
## 36    63.93313 53.78874  74.07751
## 37    62.39403 52.24863  72.53942
## 38    59.81258 49.66496  69.96020
## 39    36.84825 26.65175  47.04475
## 40    56.27021 46.11846  66.42196
## 41    60.50477 50.35781  70.65172
## 42    74.92669 64.78265  85.07073
## 43    60.27675 50.12958  70.42392
## 44    76.61237 66.46731  86.75742
## 45    67.63022 57.48730  77.77315
## 46    74.63353 64.48963  84.77742
## 47    59.54385 49.39596  69.69173
## 48    66.80774 56.66461  76.95087
## 49    61.93800 51.79226  72.08374
## 50    54.58453 44.43038  64.73868
## 51    69.76379 59.62108  79.90649
## 52    76.93810 66.79282  87.08338
## 53    86.66944 76.51247  96.82641
## 54    62.15787 52.01230  72.30344
## 55    62.56504 52.41977  72.71031
## 56    83.81926 73.66668  93.97183
## 57    79.75571 69.60801  89.90341
## 58    58.46892 48.31988  68.61796
## 59    69.97551 59.83281  80.11822
## 60    54.76368 44.60980  64.91757
## 61    51.49819 41.33891  61.65747
## 62    73.58303 63.43959  83.72647
## 63    76.19705 66.05228  86.34183
## 64    59.71486 49.56714  69.86257
## 65    68.14325 58.00042  78.28608
## 66    82.82576 72.67454  92.97699
## 67    73.33059 63.18724  83.47393
## 68    66.02598 55.88258  76.16937
## 69    77.40227 67.25665  87.54790
## 70    77.54071 67.39498  87.68644
## 71    65.00805 54.86423  75.15187
## 72    55.07313 44.91971  65.22656
## 73    82.75247 72.60134  92.90361
## 74    62.65462 52.50941  72.79982
## 75    82.08472 71.93443  92.23501
## 76    57.78488 47.63505  67.93471
## 77    64.82890 54.68499  74.97281
## 78    68.77029 58.62754  78.91304
## 79    70.63513 60.49239  80.77787
## 80    61.88100 51.73521  72.02678
## 81    55.52916 45.37639  65.68193
## 82    83.47723 73.32514  93.62933
## 83    61.19695 51.05061  71.34330
## 84    77.63029 67.48449  87.77609
## 85    52.33696 42.17916  62.49475
## 86    61.11552 50.96911  71.26193
## 87    65.93640 55.79297  76.07982
## 88    68.79472 58.65198  78.93747
## 89    72.02764 61.88468  82.17061
## 90    69.21004 59.06732  79.35275
## 91    77.51628 67.37057  87.66199
## 92    78.25733 68.11102  88.40364
## 93    69.47062 59.32792  79.61333
## 94    76.20520 66.06042  86.34998
## 95    51.80764 41.64891  61.96636
## 96    57.90703 47.75734  68.05671
## 97    83.53424 73.38206  93.68641
## 98    67.02761 56.88454  77.17068
## 99    70.24425 60.10153  80.38696
## 100   62.19044 52.04490  72.33599
## 101   68.59928 58.45652  78.74205
## 102   63.24908 53.10428  73.39389
## 103   65.26864 55.12494  75.41234
## 104   62.95592 52.81092  73.10092
## 105   62.91521 52.77018  73.06023
## 106   84.43001 74.27656  94.58345
## 107   71.17259 61.02979  81.31539
## 108   63.67254 53.52800  73.81708
## 109   83.91698 73.76427  94.06968
## 110   83.34694 73.19502  93.49886
## 111   84.37301 74.21964  94.52637
## 112   72.75241 62.60925  82.89556
## 113   73.26544 63.12212  83.40876
## 114   58.68879 48.54000  68.83759
## 115   84.34858 74.19525  94.50190
## 116   65.63509 55.49155  75.77864
## 117   81.09122 70.94211  91.24034
## 118   74.78825 64.64428  84.93222
## 119   64.03899 53.89467  74.18332
## 120   62.34517 52.19974  72.49060
## 121   66.30285 56.15956  76.44614
## 122   53.97378 43.81868  64.12887
## 123   75.11398 64.96985  85.25812
## 124   74.11235 63.96870  84.25600
## 125   76.84038 66.69517  86.98559
## 126   64.50316 54.35909  74.64724
## 127   62.36146 52.21604  72.50687
## 128   67.21491 57.07189  77.35793
## 129   67.45107 57.30810  77.59403
## 130   77.91531 67.76928  88.06134
## 131   52.21481 42.05680  62.37281
## 132   66.76702 56.62388  76.91017
## 133   70.61884 60.47610  80.76158
## 134   86.79973 76.64254  96.95692
## 135   67.81752 57.67463  77.96041
## 136   82.36159 72.21096  92.51222
## 137   59.89401 49.74647  70.04155
## 138   69.49505 59.35235  79.63776
## 139   71.52276 61.37990  81.66562
## 140   69.63349 59.49079  79.77619
## 141   67.32892 57.18592  77.47191
## 142   59.05524 48.90685  69.20364
## 143   61.53897 51.39292  71.68503
## 144   69.78822 59.64551  79.93092
## 145   76.62865 66.48359  86.77372
## 146   62.64647 52.50126  72.79169
## 147   57.21484 47.06432  67.36537
## 148   86.51471 76.35800  96.67142
## 149   83.28179 73.12996  93.43362
## 150   74.66610 64.52219  84.81001
## 151   71.33546 61.19263  81.47829
## 152   70.76542 60.62267  80.90818
## 153   54.92655 44.77291  65.08019
## 154   60.73278 50.58603  70.87953
## 155   77.63029 67.48449  87.77609
## 156   59.93473 49.78723  70.08223
## 157   59.64971 49.50193  69.79749
## 158   80.94464 70.79569  91.09360
## 159   62.14973 52.00415  72.29530
## 160   67.14976 57.00672  77.29280
## 161   83.59124 73.43899  93.74350
## 162   83.39580 73.24381  93.54779
## 163   68.90059 58.75785  79.04333
## 164   87.19061 77.03275  97.34848
## 165   58.30605 48.15683  68.45528
## 166   78.84365 68.69682  88.99048
## 167   80.07330 69.92528  90.22132
## 168   59.28326 49.13510  69.43141
## 169   92.94798 82.77848 103.11748
## 170   56.44936 46.29785  66.60087
## 171   68.65629 58.51353  78.79905
## 172   64.00642 53.86207  74.15076
## 173   57.68716 47.53721  67.83710
## 174   51.09916 40.93915  61.25918
## 175   70.21981 60.07710  80.36253
## 176   47.66266 37.49568  57.82964
## 177   85.98539 75.82955  96.14123
## 178   51.94608 41.78760  62.10456
## 179   66.44129 56.29804  76.58453
## 180   85.17920 75.02463  95.33377
## 181   77.25569 67.11018  87.40121
## 182   63.03736 52.89241  73.18230
## 183   75.05698 64.91287  85.20109
## 184   76.65308 66.50800  86.79816
## 185   70.97715 60.83437  81.11993
## 186   50.61056 40.44963  60.77150
## 187   69.67421 59.53151  79.81691
## 188   78.38762 68.24120  88.53405
## 189   69.07160 58.92887  79.21432
## 190   53.35488 43.19880  63.51096
## 191   64.98362 54.83979  75.12746
## 192   67.14162 56.99858  77.28466
## 193   72.08465 61.94167  82.22762
## 194   83.49352 73.34140  93.64564
## 195   91.27045 81.10467 101.43622
## 196   63.78655 53.64208  73.93102
## 197   62.82563 52.68054  72.97072
## 198   67.30449 57.16149  77.44748
## 199   90.55383 80.38957 100.71809
## 200   74.85340 64.70939  84.99740
## 201   76.11562 65.97090  86.26035
## 202   58.00475 47.85518  68.15432
## 203   82.54889 72.39802  92.69976
## 204   76.48207 66.33711  86.62704
## 205   53.03729 42.88068  63.19389
## 206   62.50804 52.36272  72.65335
## 207   67.31263 57.16963  77.45563
## 208   70.58627 60.44353  80.72900
## 209   74.69053 64.54661  84.83445
## 210   57.41843 47.26815  67.56870
## 211   59.13668 48.98837  69.28499
## 212   58.43635 48.28727  68.58542
## 213   54.03078 43.87578  64.18578
## 214   80.31760 70.16933  90.46588
## 215   83.64824 73.49591  93.80058
## 216   66.64487 56.50169  76.78805
## 217   87.08475 76.92707  97.24243
## 218   76.88924 66.74400  87.03449
## 219   89.70692 79.54437  99.86946
## 220   79.18567 69.03853  89.33282
## 221   58.08618 47.93671  68.23566
## 222   52.23924 42.08127  62.39720
## 223   41.18053 30.99724  51.36382
## 224   66.80774 56.66461  76.95087
## 225   68.99831 58.85558  79.14104
## 226   75.30128 65.15704  85.44552
## 227   76.49836 66.35338  86.64333
## 228   67.48364 57.34068  77.62660
## 229   64.05528 53.91096  74.19959
## 230   72.81755 62.67438  82.96073
## 231   73.68889 63.54542  83.83237
## 232   62.53247 52.38717  72.67776
## 233   72.94785 62.80463  83.09106
## 234   69.64978 59.50708  79.79248
## 235   72.67097 62.52784  82.81410
## 236   74.81268 64.66870  84.95666
## 237   73.43645 63.29307  83.57983
## 238   59.95916 49.81169  70.10663
## 239   72.27195 62.12893  82.41497
## 240   68.56671 58.42394  78.70948
## 241   72.42667 62.28361  82.56973
## 242   64.50316 54.35909  74.64724
## 243   84.57659 74.42293  94.73025
## 244   65.48037 55.33676  75.62398
## 245   71.87292 61.72999  82.01585
## 246   64.93476 54.79091  75.07862
## 247   64.88590 54.74202  75.02978
## 248   74.26707 64.12335  84.41080
## 249   79.44626 69.29887  89.59365
## 250   69.17746 59.03474  79.32018
## 251   75.92832 65.78371  86.07293
## 252   75.99347 65.84882  86.13812
## 253   68.04553 57.90269  78.18838
## 254   77.92345 67.77741  88.06949
## 255   64.64974 54.50575  74.79374
## 256   90.58640 80.42207 100.75073
## 257   56.61223 46.46094  66.76353
## 258   70.78985 60.64709  80.93261
## 259   65.71653 55.57302  75.86004
## 260   79.69056 69.54293  89.83819
## 261   77.64658 67.50076  87.79239
## 262   76.81595 66.67076  86.96115
## 263   66.63673 56.49355  76.77991
## 264   73.66446 63.52100  83.80793
## 265   80.62705 70.47845  90.77565
## 266   68.76215 58.61940  78.90490
## 267   67.10090 56.95785  77.24395
## 268   55.94447 45.79228  66.09666
## 269   57.85817 47.70843  68.00791
## 270   79.91858 69.77072  90.06644
## 271   61.30282 51.15656  71.44907
## 272   91.34374 81.17781 101.50967
## 273   60.20346 50.05622  70.35070
## 274   62.48361 52.33828  72.62894
## 275   75.03255 64.88846  85.17665
## 276   67.54879 57.40584  77.69173
## 277   89.53591 79.37370  99.69811
## 278   58.28977 48.14053  68.43901
## 279   64.65789 54.51390  74.80188
## 280   91.89749 81.73035 102.06462
## 281   59.34841 49.20032  69.49649
## 282   65.26050 55.11679  75.40420
## 283   79.96744 69.81953  90.11535
## 284   84.43815 74.28469  94.59161
## 285   71.84849 61.70557  81.99141
## 286   62.80934 52.66424  72.95444
## 287   85.43979 75.28481  95.59476
## 288   72.50810 62.36502  82.65119
## 289   61.78328 51.63741  71.92914
## 290   80.05702 69.90901  90.20502
## 291   71.90549 61.76256  82.04843
## 292   94.49522 84.32203 104.66841
## 293   66.40057 56.25731  76.54383
## 294   63.42824 53.28355  73.57293
## 295   66.17256 56.02922  76.31589
## 296   60.66763 50.52083  70.81444
## 297   58.20833 48.05900  68.35767
## 298   57.92331 47.77365  68.07298
## 299   80.28503 70.13679  90.43327
## 300   78.00488 67.85878  88.15099
## 301   65.93640 55.79297  76.07982
## 302   82.70361 72.55254  92.85468
## 303   67.11719 56.97414  77.26023
## 304   81.46582 71.31627  91.61537
## 305   54.14479 43.98996  64.29961
## 306   71.39246 61.24962  81.53530
## 307   73.50974 63.36633  83.65315
## 308   66.48200 56.33877  76.62524
## 309   64.45430 54.31021  74.59840
## 310   67.04390 56.90083  77.18696
## 311   51.48190 41.32259  61.64122
## 312   65.18721 55.04347  75.33094
## 313   48.66429 38.49947  58.82912
## 314   73.34687 63.20352  83.49022
## 315   61.05852 50.91205  71.20498
## 316   76.42507 66.28014  86.57000
## 317   59.42984 49.28184  69.57784
## 318   58.63993 48.49109  68.78878
## 319   69.03903 58.89630  79.18175
## 320   62.69533 52.55016  72.84051
## 321   78.91694 68.77005  89.06384
## 322   60.07317 49.92580  70.22053
## 323   88.70528 78.54468  98.86589
## 324   51.27018 41.11048  61.42988
## 325   85.04891 74.89454  95.20328
## 326   92.34537 82.17724 102.51350
## 327   67.53250 57.38955  77.67545
## 328   74.14492 64.00126  84.28859
## 329   57.71973 47.56982  67.86964
## 330   58.59922 48.45032  68.74811
## 331   79.20196 69.05480  89.34912
## 332   68.43642 58.29363  78.57920
## 333   60.00802 49.86059  70.15545
## 334   77.07654 66.93116  87.22192
## 335   61.25396 51.10766  71.40025
## 336   60.50477 50.35781  70.65172
## 337   59.49499 49.34705  69.64292
## 338   63.20022 53.05539  73.34506
## 339   68.87616 58.73342  79.01890
## 340   63.07807 52.93316  73.22299
## 341   76.89738 66.75213  87.04264
## 342   58.23276 48.08346  68.38207
## 343   75.96090 65.81627  86.10552
## 344   80.31760 70.16933  90.46588
## 345   72.06022 61.91725  82.20319
## 346   61.75885 51.61297  71.90473
## 347   69.83708 59.69437  79.97978
## 348   74.01463 63.87102  84.15824
## 349   91.00171 80.83651 101.16691
## 350   68.92502 58.78228  79.06775
## 351   43.03722 32.85903  53.21541
## 352   82.82576 72.67454  92.97699
## 353   73.45274 63.30935  83.59612
## 354   81.27852 71.12919  91.42785
## 355   71.18073 61.03793  81.32354
## 356   65.83053 55.68707  75.97400
## 357   90.03265 79.86945 100.19585
## 358   61.70999 51.56407  71.85590
## 359   67.24748 57.10447  77.39050
## 360   66.97875 56.83567  77.12183
## 361   75.47229 65.32796  85.61663
## 362   77.79316 67.64723  87.93909
## 363   77.71987 67.57399  87.86574
## 364   63.46895 53.32429  73.61362
## 365   75.52115 65.37679  85.66552
## 366   60.11388 49.96656  70.26121
## 367   63.33866 53.19391  73.48341
## 368   63.50153 53.35688  73.64617
## 369   65.06506 54.92126  75.20885
## 370   74.96740 64.82334  85.11147
## 371   76.71009 66.56497  86.85521
## 372   76.49022 66.34525  86.63519
## 373   75.52115 65.37679  85.66552
## 374   78.27362 68.12729  88.41994
## 375   76.35178 66.20690  86.49666
## 376   72.23123 62.08822  82.37424
## 377   77.02768 66.88233  87.17302
## 378   60.60249 50.45562  70.74935
## 379   76.75895 66.61379  86.90410
## 380   75.03255 64.88846  85.17665
## 381   88.14339 77.98383  98.30295
## 382   67.95596 57.81309  78.09882
## 383   61.31910 51.17286  71.46534
## 384   62.80934 52.66424  72.95444
## 385   72.01950 61.87654  82.16246
## 386   71.11559 60.97279  81.25838
## 387   75.18728 65.04310  85.33145
## 388   67.75237 57.60947  77.89527
## 389   75.52930 65.38493  85.67367
## 390   57.84188 47.69212  67.99164
## 391   55.87118 45.71889  66.02347
## 392   63.65625 53.51170  73.80080
## 393   71.08301 60.94022  81.22580
## 394   83.90883 73.75614  94.06153
## 395   79.14496 68.99785  89.29206
## 396   70.45597 60.31325  80.59870
## 397   62.01943 51.87376  72.16511
## 398   61.98686 51.84116  72.13256
## 399   71.58790 61.44503  81.73077
## 400   58.21648 48.06715  68.36580
## 401   64.00642 53.86207  74.15076
## 402   65.88754 55.74409  76.03098
## 403   71.06673 60.92394  81.20952
## 404   61.58783 51.44182  71.73385
## 405   67.01132 56.86825  77.15440
## 406   54.46238 44.30804  64.61672
## 407   62.91521 52.77018  73.06023
## 408   61.62855 51.48257  71.77454
## 409   94.45451 84.28142 104.62760
## 410   65.52923 55.38564  75.67282
## 411   69.29147 59.14876  79.43418
## 412   74.86154 64.71753  85.00555
## 413   63.46081 53.31614  73.60548
## 414   82.50817 72.35735  92.65899
## 415   72.91527 62.77207  83.05848
## 416   69.94294 59.80024  80.08564
## 417   63.33052 53.18576  73.47527
## 418   69.42991 59.28720  79.57261
## 419   71.82406 61.68114  81.96698
## 420   70.13024 59.98753  80.27295
## 421   71.12373 60.98093  81.26653
## 422   78.72150 68.57478  88.86822
## 423   49.14475 38.98092  59.30859
## 424   62.67090 52.52571  72.81610
## 425   80.55376 70.40524  90.70229
## 426   70.83871 60.69595  80.98147
## 427   71.98693 61.84398  82.12988
## 428   71.09116 60.94836  81.23395
## 429   89.98379 79.82069 100.14689
## 430   95.05712 84.88253 105.23171
## 431   71.58790 61.44503  81.73077
## 432   62.07644 51.93080  72.22207
## 433   90.96100 80.79588 101.12611
## 434   78.19218 68.04592  88.33844
## 435   52.25552 42.09759  62.41346
## 436   48.11869 37.95270  58.28467
## 437   68.33055 58.18775  78.47335
## 438   80.26060 70.11239  90.40881
## 439   75.52115 65.37679  85.66552
## 440   68.72958 58.58682  78.87233
## 441   57.73602 47.58613  67.88590
## 442   70.08138 59.93867  80.22409
## 443   69.16932 59.02660  79.31204
## 444   84.76389 74.60995  94.91783
## 445   67.85824 57.71536  78.00111
## 446   78.00488 67.85878  88.15099
## 447   69.50320 59.36049  79.64590
## 448   71.72634 61.58344  81.86924
## 449   60.14646 49.99916  70.29375
## 450   67.13347 56.99043  77.27652
## 451   74.46251 64.31870  84.60633
## 452   68.45270 58.30992  78.59549
## 453   70.21981 60.07710  80.36253
## 454   55.90376 45.75151  66.05600
## 455   72.75241 62.60925  82.89556
## 456   66.22142 56.07810  76.36474
## 457   69.10417 58.96145  79.24689
## 458   59.02267 48.87424  69.17110
## 459   78.48534 68.33883  88.63185
## 460   82.51632 72.36549  92.66714
## 461   61.68556 51.53962  71.83149
## 462   57.54872 47.39861  67.69883
## 463   72.57325 62.43015  82.71635
## 464   80.47233 70.32389  90.62076
## 465   60.26046 50.11328  70.40765
## 466   56.63666 46.48540  66.78792
## 467   59.95916 49.81169  70.10663
## 468   53.03729 42.88068  63.19389
## 469   89.96751 79.80444 100.13057
## 470   64.59274 54.44872  74.73677
## 471   81.83227 71.68229  91.98225
## 472   71.88921 61.74628  82.03214
## 473   76.28663 66.14180  86.43147
## 474   93.45287 83.28219 103.62355
## 475   59.28326 49.13510  69.43141
## 476   79.35668 69.20938  89.50399
## 477   68.17583 58.03300  78.31865
## 478   74.29965 64.15591  84.44338
## 479   62.02758 51.88191  72.17325
## 480   66.73445 56.59130  76.87760
## 481   53.51775 43.36193  63.67357
## 482   66.79145 56.64832  76.93459
## 483   67.06833 56.92527  77.21139
## 484   74.69867 64.55475  84.84260
## 485   72.41038 62.26733  82.55344
## 486   73.28172 63.13840  83.42505
## 487   73.90062 63.75706  84.04418
## 488   73.16772 63.02443  83.31100
## 489   51.90536 41.74681  62.06391
## 490   81.64497 71.49522  91.79473
## 491   80.23617 70.08798  90.38436
## 492   76.41693 66.27200  86.56185
## 493   61.09109 50.94465  71.23752
## 494   73.24101 63.09770  83.38432
## 495   69.32404 59.18133  79.46675
## 496   73.02928 62.88604  83.17252
## 497   72.61397 62.47086  82.75708
## 498   86.04240 75.88646  96.19833
## 499   80.92021 70.77129  91.06914
## 500   65.00805 54.86423  75.15187
## 501   67.98039 57.83753  78.12324
## 502   78.49349 68.34697  88.64000
## 503   71.63676 61.49388  81.77964
## 504   59.95916 49.81169  70.10663
## 505   58.43635 48.28727  68.58542
## 506   90.21181 80.04825 100.37537
## 507   65.10577 54.96200  75.24955
## 508   79.74757 69.59988  89.89526
## 509   61.56340 51.41737  71.70944
## 510   71.12373 60.98093  81.26653
## 511   58.88423 48.73565  69.03281
## 512   87.84208 77.68307  98.00110
## 513   43.92485 33.74897  54.10073
## 514   74.94297 64.79892  85.08702
## 515   59.25069 49.10250  69.39887
## 516   93.55874 83.38780 103.72967
## 517   63.96570 53.82133  74.11007
## 518   56.13992 45.98799  66.29184
## 519   79.55213 69.40463  89.69962
## 520   60.34190 50.19479  70.48901
## 521   60.07317 49.92580  70.22053
## 522   66.46572 56.32248  76.60896
## 523   69.34847 59.20576  79.49118
## 524   63.96570 53.82133  74.11007
## 525   68.89244 58.74971  79.03518
## 526   70.78171 60.63895  80.92446
## 527   77.07654 66.93116  87.22192
## 528   53.87606 43.72081  64.03130
## 529   62.63019 52.48496  72.77541
## 530   71.56347 61.42061  81.70634
## 531   63.42824 53.28355  73.57293
## 532   81.47396 71.32441  91.62352
## 533   85.21177 75.05715  95.36639
## 534   52.02751 41.86917  62.18585
## 535   71.63676 61.49388  81.77964
## 536   87.17433 77.01649  97.33216
## 537   70.61070 60.46796  80.75344
## 538   72.42667 62.28361  82.56973
## 539   71.44132 61.29848  81.58417
## 540   67.80123 57.65834  77.94412
## 541   52.32067 42.16285  62.47849
## 542   79.83714 69.68937  89.98492
## 543   74.55209 64.40824  84.69595
## 544   83.43652 73.28447  93.58856
## 545   67.76866 57.62576  77.91156
## 546   69.06346 58.92073  79.20618
## 547   69.36476 59.22205  79.50747
## 548   67.06833 56.92527  77.21139
## 549   71.00972 60.86694  81.15250
## 550   76.89738 66.75213  87.04264
## 551   75.26057 65.11635  85.40478
## 552   74.34036 64.19661  84.48412
## 553   64.32401 54.17984  74.46818
## 554   67.66279 57.51988  77.80571
## 555   71.52276 61.37990  81.66562
## 556   67.97224 57.82938  78.11510
## 557   78.44463 68.29815  88.59110
## 558   64.86147 54.71758  75.00536
## 559   62.24745 52.10194  72.39295
## 560   59.51942 49.37150  69.66733
## 561   84.94304 74.78883  95.09725
## 562   66.26213 56.11883  76.40544
## 563   88.95773 78.79664  99.11881
## 564   85.69223 75.53686  95.84760
## 565   70.50483 60.36210  80.64756
## 566   73.28172 63.13840  83.42505
## 567   76.35178 66.20690  86.49666
## 568   65.16278 55.01903  75.30653
## 569   71.07487 60.93208  81.21766
## 570   75.99347 65.84882  86.13812
## 571   60.94451 50.79795  71.09107
## 572   55.75718 45.60473  65.90963
## 573   75.35014 65.20587  85.49441
## 574   68.65629 58.51353  78.79905
## 575   58.50149 48.35249  68.65050
## 576   88.22482 78.06511  98.38453
## 577   74.65796 64.51405  84.80186
## 578   69.34847 59.20576  79.49118
## 579   54.02264 43.86762  64.17765
## 580   50.77343 40.61280  60.93405
## 581   76.17262 66.02786  86.31739
## 582   75.93647 65.79185  86.08108
## 583   77.54885 67.40312  87.69459
## 584   67.64651 57.50359  77.78943
## 585   81.62054 71.47081  91.77027
## 586   67.78495 57.64205  77.92784
## 587   69.29147 59.14876  79.43418
## 588   78.19218 68.04592  88.33844
## 589   77.15797 67.01253  87.30341
## 590   64.61717 54.47316  74.76118
## 591   58.28977 48.14053  68.43901
## 592   84.78017 74.62621  94.93414
## 593   68.85173 58.70899  78.99447
## 594   65.80610 55.66263  75.94958
## 595   65.04063 54.89682  75.18443
## 596   68.77844 58.63569  78.92119
## 597   63.63182 53.48726  73.77639
## 598   60.84679 50.70014  70.99343
## 599   52.54869 42.39126  62.70612
## 600   86.49028 76.33361  96.64695
## 601   69.34033 59.19762  79.48304
## 602   75.96090 65.81627  86.10552
## 603   76.00976 65.86510  86.15441
## 604   66.56344 56.42023  76.70664
## 605   80.74106 70.59233  90.88979
## 606   67.29634 57.15334  77.43934
## 607   61.78328 51.63741  71.92914
## 608   90.26067 80.09701 100.42433
## 609   61.62855 51.48257  71.77454
## 610   85.65966 75.50434  95.81498
## 611   72.01136 61.86840  82.15432
## 612   86.44957 76.29296  96.60617
## 613   75.29314 65.14890  85.43738
## 614   70.49669 60.35396  80.63942
## 615   63.33052 53.18576  73.47527
## 616   54.54381 44.38960  64.69803
## 617   64.11228 53.96800  74.25656
## 618   66.51458 56.37136  76.65780
## 619   81.09122 70.94211  91.24034
## 620   90.07337 79.91009 100.23665
## 621   73.79476 63.65124  83.93828
## 622   69.91851 59.77581  80.06121
## 623   64.00642 53.86207  74.15076
## 624   72.31266 62.16963  82.45569
## 625   60.56991 50.42302  70.71681
## 626   76.14819 66.00345  86.29294
## 627   82.14986 71.99949  92.30023
## 628   66.61230 56.46911  76.75549
## 629   71.72634 61.58344  81.86924
## 630   76.89738 66.75213  87.04264
## 631   84.89418 74.74005  95.04832
## 632   73.30616 63.16282  83.44949
## 633   64.53574 54.39168  74.67979
## 634   67.08461 56.94156  77.22767
## 635   68.24097 58.09816  78.38379
## 636   81.24595 71.09665  91.39524
## 637   68.69700 58.55425  78.83976
## 638   54.07150 43.91656  64.22644
## 639   65.56995 55.42638  75.71352
## 640   84.12056 73.96756  94.27356
## 641   79.17753 69.03039  89.32467
## 642   62.58133 52.43607  72.72659
## 643   60.26046 50.11328  70.40765
## 644   57.98032 47.83072  68.12992
## 645   90.36653 80.20265 100.53041
## 646   74.56838 64.42452  84.71224
## 647   65.43151 55.28788  75.57514
## 648   63.74583 53.60133  73.89033
## 649   61.87285 51.72706  72.01864
## 650   55.78161 45.62919  65.93402
## 651   61.14809 51.00171  71.29448
## 652   62.45103 52.30568  72.59639
## 653   72.75241 62.60925  82.89556
## 654   52.59755 42.44020  62.75489
## 655   68.50156 58.35878  78.64434
## 656   71.32731 61.18449  81.47014
## 657   72.07651 61.93353  82.21948
## 658   87.68736 77.52862  97.84610
## 659   89.07173 78.91043  99.23304
## 660   69.02274 58.88001  79.16547
## 661   74.45437 64.31056  84.59818
## 662   69.27518 59.13247  79.41790
## 663   77.26384 67.11832  87.40936
## 664   69.40548 59.26277  79.54819
## 665   69.11232 58.96959  79.25504
## 666   70.08952 59.94681  80.23223
## 667   80.07330 69.92528  90.22132
## 668   52.19852 42.04048  62.35656
## 669   45.44766 35.27558  55.61975
## 670   69.64978 59.50708  79.79248
## 671   87.43492 77.27663  97.59320
## 672   63.53410 53.38948  73.67873
## 673   61.27839 51.13211  71.42466
## 674   59.56013 49.41226  69.70800
## 675   60.70835 50.56158  70.85512
## 676   51.62848 41.46944  61.78753
## 677   61.93800 51.79226  72.08374
## 678   85.45607 75.30108  95.61107
## 679   61.85657 51.71076  72.00237
## 680   66.53086 56.38765  76.67408
## 681   52.49983 42.34231  62.65734
## 682   75.97718 65.83254  86.12182
## 683   64.03899 53.89467  74.18332
## 684   83.10264 72.95105  93.25423
## 685   65.65952 55.51599  75.80306
## 686   79.92672 69.77885  90.07459
## 687   74.23450 64.09079  84.37821
## 688   64.91848 54.77461  75.06234
## 689   76.27034 66.12552  86.41517
## 690   58.53407 48.38510  68.68303
## 691   68.25726 58.11445  78.40007
## 692   55.63503 45.48241  65.78765
## 693   56.75881 46.60771  66.90992
## 694   57.74416 47.59428  67.89404
## 695   71.08301 60.94022  81.22580
## 696   79.60913 69.46158  89.75668
## 697   63.37938 53.23466  73.52410
## 698   66.61230 56.46911  76.75549
## 699   61.21324 51.06691  71.35957
## 700   75.77360 65.62908  85.91811
## 701   64.25886 54.11466  74.40306
## 702   78.89251 68.74564  89.03938
## 703   83.90069 73.74800  94.05338
## 704   55.95262 45.80044  66.10480
## 705   64.31587 54.17170  74.46004
## 706   62.79305 52.64794  72.93817
## 707   62.35331 52.20789  72.49874
## 708   66.14813 56.00478  76.29147
## 709   63.13508 52.99020  73.27996
## 710   75.62702 65.48259  85.77144
## 711   75.84689 65.70233  85.99145
## 712   65.43151 55.28788  75.57514
## 713   65.47223 55.32861  75.61584
## 714   73.62375 63.48029  83.76720
## 715   75.17913 65.03496  85.32331
## 716   70.64327 60.50053  80.78601
## 717   71.96250 61.81955  82.10545
## 718   57.59758 47.44753  67.74763
## 719   47.95582 37.78948  58.12216
## 720   70.07323 59.93053  80.21594
## 721   66.21327 56.06995  76.35660
## 722   84.30786 74.15459  94.46113
## 723   68.05368 57.91083  78.19652
## 724   62.93964 52.79463  73.08465
## 725   81.15637 71.00718  91.30556
## 726   75.54558 65.40120  85.68996
## 727   53.00471 42.84805  63.16137
## 728   56.27835 46.12662  66.43009
## 729   76.28663 66.14180  86.43147
## 730   52.14152 41.98338  62.29965
## 731   55.96890 45.81675  66.12106
## 732   69.42991 59.28720  79.57261
## 733   85.08148 74.92706  95.23590
## 734   82.19058 72.04016  92.34100
## 735   77.45928 67.31361  87.60495
## 736   62.39403 52.24863  72.53942
## 737   68.10254 57.95970  78.24537
## 738   56.24578 46.09400  66.39756
## 739   79.91043 69.76258  90.05829
## 740   74.35665 64.21289  84.50041
## 741   71.35174 61.20891  81.49458
## 742   59.56013 49.41226  69.70800
## 743   64.23443 54.09022  74.37865
## 744   66.79145 56.64832  76.93459
## 745   57.19041 47.03986  67.34097
## 746   88.15968 78.00008  98.31927
## 747   84.74760 74.59369  94.90152
## 748   62.14973 52.00415  72.29530
## 749   78.33876 68.19238  88.48515
## 750   57.68716 47.53721  67.83710
## 751   59.46241 49.31444  69.61038
## 752   54.74740 44.59349  64.90130
## 753   70.74099 60.59824  80.88374
## 754   79.16939 69.02226  89.31652
## 755   57.03569 46.88494  67.18644
## 756   55.57802 45.42532  65.73072
## 757   71.59605 61.45317  81.73892
## 758   75.74917 65.60467  85.89367
## 759   71.07487 60.93208  81.21766
## 760   77.95602 67.80996  88.10209
## 761   50.26854 40.10695  60.43013
## 762   48.33042 38.16488  58.49595
## 763   75.65959 65.51515  85.80404
## 764   66.01783 55.87444  76.16123
## 765   61.53083 51.38477  71.67690
## 766   70.53741 60.39467  80.68014
## 767   79.18567 69.03853  89.33282
## 768   71.22145 61.07864  81.36426
## 769   72.78498 62.64182  82.92814
## 770   68.08625 57.94341  78.22909
## 771   60.26046 50.11328  70.40765
## 772   62.17416 52.02860  72.31972
## 773   76.66123 66.51614  86.80631
## 774   69.04717 58.90444  79.18989
## 775   76.92181 66.77655  87.06708
## 776   87.70365 77.54488  97.86241
## 777   66.99504 56.85196  77.13812
## 778   70.78985 60.64709  80.93261
## 779   73.78661 63.64310  83.93013
## 780   50.83858 40.67807  60.99908
## 781   59.11225 48.96391  69.26058
## 782   67.33706 57.19407  77.48005
## 783   66.49829 56.35506  76.64152
## 784   75.35014 65.20587  85.49441
## 785   60.56991 50.42302  70.71681
## 786   86.36813 76.21167  96.52460
## 787   46.95419 36.78563  57.12274
## 788   82.47560 72.32482  92.62638
## 789   82.07657 71.92629  92.22685
## 790   51.13988 40.97994  61.29982
## 791   85.70852 75.55312  95.86392
## 792   65.53737 55.39379  75.68096
## 793  101.36823 91.17581 111.56066
## 794   48.27341 38.10776  58.43907
## 795   59.76372 49.61605  69.91138
## 796   64.58460 54.44057  74.72863
## 797   61.75885 51.61297  71.90473
## 798   76.36807 66.22318  86.51295
## 799   73.85990 63.71636  84.00345
## 800   69.38105 59.23834  79.52376
## 801   57.93146 47.78180  68.08111
## 802   60.83050 50.68384  70.97716
## 803   58.11061 47.96117  68.26006
## 804   77.17426 67.02881  87.31971
## 805   62.92335 52.77833  73.06837
## 806   67.98853 57.84567  78.13139
## 807   83.76225 73.60976  93.91474
## 808   70.35825 60.21553  80.50097
## 809   75.93647 65.79185  86.08108
## 810   76.92181 66.77655  87.06708
## 811   84.14499 73.99196  94.29802
## 812   77.22312 67.07763  87.36861
## 813   78.74593 68.59919  88.89267
## 814   54.15293 43.99812  64.30774
## 815   67.67908 57.53617  77.82200
## 816   75.03255 64.88846  85.17665
## 817   69.47877 59.33606  79.62147
## 818   50.12196 39.96008  60.28384
## 819   68.40384 58.26105  78.54663
## 820   82.75247 72.60134  92.90361
## 821   67.32077 57.17778  77.46377
## 822   79.78014 69.63242  89.92786
## 823   76.54722 66.40221  86.69223
## 824   60.94451 50.79795  71.09107
## 825   55.35001 45.19698  65.50303
## 826   80.25246 70.10425  90.40066
## 827   85.69223 75.53686  95.84760
## 828   53.38745 43.23142  63.54348
## 829   77.57328 67.42753  87.71904
## 830   81.49025 71.34067  91.63983
## 831   67.53250 57.38955  77.67545
## 832   75.83875 65.69419  85.98330
## 833   72.02764 61.88468  82.17061
## 834   58.10247 47.95301  68.25192
## 835   74.43808 64.29428  84.58188
## 836   69.73121 59.58851  79.87391
## 837   84.21828 74.06514  94.37142
## 838   52.04380 41.88549  62.20210
## 839   68.01296 57.87011  78.15581
## 840   77.81759 67.67164  87.96354
## 841   81.31924 71.16986  91.46862
## 842   64.02270 53.87837  74.16704
## 843   74.29965 64.15591  84.44338
## 844   65.04877 54.90497  75.19257
## 845   61.19695 51.05061  71.34330
## 846   75.40715 65.26285  85.55145
## 847   61.01780 50.87130  71.16430
## 848   58.44449 48.29543  68.59356
## 849   91.44960 81.28344 101.61576
## 850   71.60419 61.46131  81.74706
## 851   64.69046 54.54649  74.83444
## 852   78.84365 68.69682  88.99048
## 853   65.63509 55.49155  75.77864
## 854   37.32057 27.12560  47.51554
## 855   68.88430 58.74156  79.02704
## 856   61.88914 51.74336  72.03492
## 857   67.10904 56.96600  77.25209
## 858   86.96260 76.80513  97.12007
## 859   55.04056 44.88709  65.19403
## 860   79.51955 69.37209  89.66702
## 861   64.60903 54.46501  74.75304
## 862   73.15957 63.01629  83.30286
## 863   66.44129 56.29804  76.58453
## 864   75.78989 65.64536  85.93441
## 865   80.94464 70.79569  91.09360
## 866   71.67748 61.53459  81.82037
## 867   53.00471 42.84805  63.16137
## 868   82.07657 71.92629  92.22685
## 869   67.94781 57.80495  78.09068
## 870   72.88270 62.73951  83.02589
## 871   68.68886 58.54610  78.83162
## 872   68.66443 58.52167  78.80719
## 873   75.43158 65.28726  85.57589
## 874   86.72644 76.56937  96.88351
## 875   78.41205 68.26561  88.55850
## 876   85.05705 74.90267  95.21143
## 877   68.21654 58.07373  78.35936
## 878   63.34680 53.20206  73.49155
## 879   76.05862 65.91393  86.20331
## 880   68.67257 58.52981  78.81533
## 881   79.56027 69.41277  89.70777
## 882   74.50323 64.35940  84.64706
## 883   58.15947 48.01008  68.30886
## 884   60.25232 50.10513  70.39951
## 885   76.38435 66.23945  86.52925
## 886   68.60743 58.46466  78.75019
## 887   68.58300 58.44023  78.72577
## 888   58.18390 48.03454  68.33326
## 889   70.92015 60.77737  81.06292
## 890   68.35498 58.21218  78.49778
## 891   75.52930 65.38493  85.67367
## 892   63.50967 53.36503  73.65431
## 893   65.08949 54.94570  75.23327
## 894   64.73932 54.59537  74.88327
## 895   94.47079 84.29766 104.64392
## 896   78.53420 68.38765  88.68076
## 897   84.04727 73.89438  94.20016
## 898   66.97875 56.83567  77.12183
## 899   53.69690 43.54137  63.85243
## 900   67.85009 57.70721  77.99297
## 901   80.52119 70.37270  90.66968
## 902   53.77019 43.61478  63.92561
## 903   70.92829 60.78552  81.07106
## 904   49.59264 39.42972  59.75556
## 905   76.36807 66.22318  86.51295
## 906   68.11882 57.97599  78.26166
## 907   82.01143 71.86123  92.16163
## 908   71.75077 61.60787  81.89367
## 909   71.05044 60.90765  81.19323
## 910   83.91698 73.76427  94.06968
## 911   70.01623 59.87352  80.15894
## 912   51.66920 41.51023  61.82818
## 913   81.13194 70.98278  91.28110
## 914   71.63676 61.49388  81.77964
## 915   63.44452 53.29984  73.58921
## 916   66.91360 56.77050  77.05671
## 917   57.96403 47.81441  68.11365
## 918   81.42510 71.27560  91.57460
## 919   75.35014 65.20587  85.49441
## 920   72.15794 62.01495  82.30093
## 921   71.55533 61.41246  81.69819
## 922   79.19382 69.04667  89.34097
## 923   80.63519 70.48658  90.78381
## 924   69.59277 59.45007  79.73548
## 925   82.58961 72.43868  92.74053
## 926   73.58303 63.43959  83.72647
## 927   78.71336 68.56665  88.86007
## 928   52.12523 41.96707  62.28339
## 929   79.53584 69.38836  89.68332
## 930   73.05371 62.91046  83.19696
## 931   51.92979 41.77128  62.08830
## 932   70.86314 60.72038  81.00591
## 933   75.31757 65.17332  85.46182
## 934   73.99834 63.85474  84.14195
## 935   68.48528 58.34249  78.62806
## 936   85.38278 75.22790  95.53767
## 937   83.34694 73.19502  93.49886
## 938   74.62538 64.48149  84.76927
## 939   62.58133 52.43607  72.72659
## 940   81.88927 71.73922  92.03933
## 941   72.62211 62.47900  82.76523
## 942   62.13344 51.98785  72.27903
## 943   68.69700 58.55425  78.83976
## 944   72.78498 62.64182  82.92814
## 945   82.58146 72.43055  92.73237
## 946   58.81094 48.66228  68.95960
## 947   65.11392 54.97015  75.25769
## 948   60.92008 50.77349  71.06666
## 949   60.08945 49.94211  70.23680
## 950   56.34350 46.19185  66.49515
## 951   73.07000 62.92674  83.21325
## 952   80.61076 70.46218  90.75935
## 953   62.53247 52.38717  72.67776
## 954   86.58800 76.43117  96.74484
## 955   86.21341 76.05720  96.36962
## 956   60.80607 50.65939  70.95275
## 957   81.02608 70.87703  91.17512
## 958   75.73288 65.58839  85.87737
## 959   57.45914 47.30892  67.60936
## 960   70.10581 59.96310  80.24852
## 961   78.78665 68.63987  88.93342
## 962   54.52753 44.37329  64.68176
## 963   51.43304 41.27364  61.59244
## 964   71.67748 61.53459  81.82037
## 965   77.85016 67.70418  87.99614
## 966   75.92018 65.77558  86.06478
## 967   63.09436 52.94945  73.23927
## 968   74.67424 64.53033  84.81816
## 969   69.30776 59.16505  79.45047
## 970   82.75247 72.60134  92.90361
## 971   76.88924 66.74400  87.03449
## 972   75.64330 65.49887  85.78774
## 973   80.60262 70.45404  90.75120
## 974   84.52773 74.37414  94.68132
## 975   55.03242 44.87893  65.18590
## 976   75.21985 65.07565  85.36405
## 977   62.12530 51.97970  72.27089
## 978   74.71496 64.57103  84.85889
## 979   55.26043 45.10728  65.41358
## 980   62.72791 52.58275  72.87306
## 981   62.31260 52.16714  72.45805
## 982   70.14652 60.00381  80.28923
## 983   65.83053 55.68707  75.97400
## 984   82.83391 72.68267  92.98515
## 985   52.97214 42.81543  63.12886
## 986   77.12540 66.97998  87.27082
## 987   62.76048 52.61535  72.90561
## 988   61.86471 51.71891  72.01051
## 989   74.40551 64.26173  84.54930
## 990   65.31750 55.17382  75.46118
## 991   82.80948 72.65827  92.96068
## 992   72.08465 61.94167  82.22762
## 993   62.36960 52.22419  72.51501
## 994   56.49008 46.33863  66.64154
## 995   71.55533 61.41246  81.69819
## 996   76.75080 66.60566  86.89595
## 997   59.13668 48.98837  69.28499
## 998   74.23450 64.09079  84.37821
## 999   73.82733 63.68380  83.97086
## 1000  85.39907 75.24416  95.55398</code></pre>
</div>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3,h4",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
